on:
  rss:
    url: 
      - http://www.ruanyifeng.com/blog/atom.xml
      - https://sspai.com/feed
jobs:
  request:
    name: make a http Request
    runs-on: ubuntu-latest
    steps:
      - name: http Request
        uses: actionsflow/axios@v1
        with:
          url: https://tauri.localhost/c/api/save/o8j4go7kbrpcdy
          method: POST
          body: |
            {
              "type":"url",
              "content":"${{ on.rss.outputs.link }}", 
              "title": "${{ on.rss.outputs.title }}",
              "folder":"收集箱"
            }
